Fix

diff --git a/.github/workflows/list-assets-in-branch.yml b/.github/workflows/list-assets-in-branch.yml
--- a/.github/workflows/list-assets-in-branch.yml
+++ b/.github/workflows/list-assets-in-branch.yml
@@ -91,8 +91,14 @@ jobs:
           echo "Path to list files: $PATH_TO_LIST"
           echo "Asset list filename: $FILE_LIST_NAME"
 
+          echo "Checking if branch $branch exists..."
+          if ! git ls-remote --heads https://github.com/${{ github.repository }}.git "$branch" | grep -q "$branch"; then
+            echo "Branch $branch NOT found in remote, skipping."
+            continue
+          fi
+
           echo "Cloning branch..."
-          git clone --depth 1 --branch "$branch" "https://github.com/${{ github.repository }}.git" "tmp-$branch"
+          git clone --depth 1 --branch "$branch" https://github.com/${{ github.repository }}.git "tmp-$branch"
 
           if [ -d "tmp-$branch/$PATH_TO_LIST" ]; then
             echo "Generating file list relative to $PATH_TO_LIST..."
